### ISSUE TITLE
UnknownFormatConversionException in SqlProUtil

### ISSUE THREAD

**Issue by donnerpeter** [kookob/mybatis-log-plugin#112]
java.util.UnknownFormatConversionException: Conversion = '施'
	at java.base/java.util.Formatter.checkText(Formatter.java:2732)
	at java.base/java.util.Formatter.parse(Formatter.java:2708)
	at java.base/java.util.Formatter.format(Formatter.java:2655)
	at java.base/java.util.Formatter.format(Formatter.java:2609)
	at java.base/java.lang.String.format(String.java:2897)
	at com.plugins.mybaitslog.util.SqlProUtil.restoreSql(SqlProUtil.java:70)
	at com.plugins.mybaitslog.util.SqlProUtil.restoreSql(SqlProUtil.java:55)
	at com.plugins.mybaitslog.filter.MyBatisLogFilter.prints(MyBatisLogFilter.java:51)
	at com.plugins.mybaitslog.filter.MyBatisLogFilter.applyFilter(MyBatisLogFilter.java:35)
	at com.intellij.execution.filters.CompositeFilter.applyFilter(CompositeFilter.java:76)

**Comment by kookob** [comment]
@donnerpeter 这个错误不是我这个插件，是另一个网友，克隆我代码后因为不遵守许可协议，后面自己改造的插件，你需要反馈给那个作者哦。
