### ISSUE TITLE
mapper.xml jump to dao exception, java.lang.Throwable: Control-flow exceptions (like ProcessCanceledException) should never be logged

### ISSUE THREAD

**Issue by c332030** [kookob/mybatis-log-plugin#115]
```
mapper.xml jump to dao exception

java.lang.Throwable: Control-flow exceptions (like ProcessCanceledException) should never be logged
	at com.intellij.openapi.diagnostic.Logger.checkException(Logger.java:195)
	at com.intellij.idea.IdeaLogger.error(IdeaLogger.java:88)
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:165)
	at x.a(x.java)
	at x.collectNavigationMarkers(x.java)
	at com.intellij.codeInsight.daemon.RelatedItemLineMarkerProvider.collectNavigationMarkers(RelatedItemLineMarkerProvider.java:31)
	at com.intellij.codeInsight.daemon.RelatedItemLineMarkerProvider.collectSlowLineMarkers(RelatedItemLineMarkerProvider.java:23)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.queryProviders(LineMarkersPass.java:187)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.lambda$doCollectInformation$3(LineMarkersPass.java:96)
	at com.intellij.codeInsight.daemon.impl.Divider.divideInsideAndOutsideInOneRoot(Divider.java:81)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.doCollectInformation(LineMarkersPass.java:83)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:54)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:399)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1110)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:392)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:629)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:581)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:391)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:367)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:170)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:182)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:365)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:181)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: com.intellij.openapi.progress.ProcessCanceledException
	at com.intellij.openapi.progress.util.AbstractProgressIndicatorBase.throwIfCanceled(AbstractProgressIndicatorBase.java:135)
	at com.intellij.openapi.progress.util.AbstractProgressIndicatorBase.checkCanceled(AbstractProgressIndicatorBase.java:126)
	at com.intellij.codeInsight.daemon.impl.DaemonProgressIndicator.checkCanceled(DaemonProgressIndicator.java:96)
	at com.intellij.openapi.progress.impl.CoreProgressManager.doCheckCanceled(CoreProgressManager.java:128)
	at com.intellij.openapi.progress.ProgressManager.checkCanceled(ProgressManager.java:227)
	at com.intellij.psi.stubs.StubIndexImpl.processElements(StubIndexImpl.java:301)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:108)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:96)
	at com.intellij.psi.impl.java.stubs.index.JavaMethodNameIndex.get(JavaMethodNameIndex.java:30)
	... 26 more
```

**Comment by c332030** [comment]
我又来提bug了，这个好像不影响使用

**Comment by kookob** [comment]
@c332030 帮忙提供下插件和IDE版本，这个功能不太完善，可能部分场景是会有问题。

**Comment by c332030** [comment]
> @c332030 帮忙提供下插件和IDE版本，这个功能不太完善，可能部分场景是会有问题。

IntelliJ IDEA 2020.2.3 (Ultimate Edition)
Build #IU-202.7660.26, built on October 6, 2020
Licensed to C C
Subscription is active until March 25, 2021
For educational use only.
Runtime version: 11.0.8+10-b944.34 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 4012M
Cores: 12
Registry: debugger.watches.in.variables=false, compiler.automake.allow.when.app.running=true, ide.balloon.shadow.size=0

![image](https://user-images.githubusercontent.com/15310784/99932158-399d0900-2d92-11eb-85a7-b8fbec7edfb5.png)

**Comment by kookob** [comment]
收到，过后我试下会不会重现，感谢
