### ISSUE TITLE
`ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'mybatislog.s' must override `getActionUpdateThread` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: MyBatisLog]

### ISSUE THREAD

**Issue by xiaoyan94** [kookob/mybatis-log-plugin#134]
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'mybatislog.s' must override `getActionUpdateThread` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: MyBatisLog]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:199)

**Comment by kookob** [comment]
新版本已修复：https://plugins.jetbrains.com/plugin/13905-mybatis-log
